# register ka 
POST http://localhost:5000/api/v1/user/register
Content-Type: application/json

{
  "name": "Gunnev aid ",
  "username": "crossfirerules",
  "email": "guneev@gmail.com",
  "password": "securePassword123"
}
###
# login
POST http://localhost:5000/api/v1/user/login
Content-Type: application/json

{
  "email": "thewoo@gmail.com",
  "password": "abcd"
}
###
# logout request
GET  http://localhost:5000/api/v1/user/logout
Content-Type: application/json

{

}
###

# now to tweet with ammar 
# chekced mongodb to get ammar's id
POST http://localhost:5000/api/v1/tweet/post
Content-Type: application/json

{
  "description": "madhu 1st tweet"
}
###
# deletting the tweet 
DELETE  http://localhost:5000/api/v1/tweet/delete/6a5b5b244772f436848a31d9
Content-Type: application/json

{

}
###
# likieng and distliking a tweet 
PUT http://localhost:5000/api/v1/tweet/like/6a5b5ee2e152bf7317af27bc
Content-Type: application/json

{
}
###
# chekcing teh bookmark
PUT  http://localhost:5000/api/v1/user/bookmark/6a5b5ee2e152bf7317af27bc
Content-Type: application/json

{

}
###
#chcking the profile 
GET http://localhost:5000/api/v1/user/profile/6a665f5a3c55266d9df9861e
Content-Type: application/json

{

}
###
# other users
GET  http://localhost:5000/api/v1/user/otheruser
Content-Type: application/json

{

}
###
#folowing and not following 
POST  http://localhost:5000/api/v1/user/follow/6a665fc13c55266d9df9861f
Content-Type: application/json

{

}
###
#get all tweets of loggend and following 
GET http://localhost:5000/api/v1/tweet/getalltweets
Content-Type: application/json

{

}
###
# only following ppl tweets
GET http://localhost:5000/api/v1/tweet/getallfollowertweets
Content-Type: application/json

{

}