# register ka 
POST http://localhost:5000/api/v1/user/register
Content-Type: application/json

{
  "name": "Ammar Mohammed ",
  "username": "amrq",
  "email": "Ammar@gmail.com",
  "password": "securePassword123"
}
###
# login
POST http://localhost:5000/api/v1/user/login
Content-Type: application/json

{
  "email": "Ammar@gmail.com",
  "password": "securePassword123"
}
###
# logout request
GET  http://localhost:5000/api/v1/user/logout
Content-Type: application/json

{

}
###

# now to tweet with ammar 
# chekced mongodb to get ammar's id
POST http://localhost:5000/api/v1/tweet/post
Content-Type: application/json

{
  "description": "this is the second tweet"
}
###
# deletting the tweet 
DELETE  http://localhost:5000/api/v1/tweet/delete/6a5b5b244772f436848a31d9
Content-Type: application/json

{

}
###
# likieng and distliking a tweet 
PUT http://localhost:5000/api/v1/tweet/like/6a5b5a3a7c0154b24ea45a29
Content-Type: application/json

{
}
###
# chekcing teh bookmark
PUT  http://localhost:5000/api/v1/user/bookmark/6a5b5a3a7c0154b24ea45a29
Content-Type: application/json

{

}
###
#chcking the profile 
GET http://localhost:5000/api/v1/user/profile/6a5a7bb35de485c19604756a
Content-Type: application/json

{

}
