# register ka 
POST http://localhost:5000/api/v1/user/register
Content-Type: application/json

{
  "name": "Gunnev aid ",
  "username": "crossfirerules",
  "email": "guneev@gmail.com",
  "password": "securePassword123"
}
###
# login
POST http://localhost:5000/api/v1/user/login
Content-Type: application/json

{
  "email": "Ammar@gmail.com",
  "password": "securePassword123"
}
###
# logout request
GET  http://localhost:5000/api/v1/user/logout
Content-Type: application/json

{

}
###

# now to tweet with ammar 
# chekced mongodb to get ammar's id
POST http://localhost:5000/api/v1/tweet/post
Content-Type: application/json

{
  "description": "random tweet"
}
###
# deletting the tweet 
DELETE  http://localhost:5000/api/v1/tweet/delete/6a5b5b244772f436848a31d9
Content-Type: application/json

{

}
###
# likieng and distliking a tweet 
PUT http://localhost:5000/api/v1/tweet/like/6a5b5ee2e152bf7317af27bc
Content-Type: application/json

{
}
###
# chekcing teh bookmark
PUT  http://localhost:5000/api/v1/user/bookmark/6a5b5ee2e152bf7317af27bc
Content-Type: application/json

{

}
###
#chcking the profile 
GET http://localhost:5000/api/v1/user/profile/6a5b754d9fff598f91d3eebf
Content-Type: application/json

{

}
###
# other users
GET  http://localhost:5000/api/v1/user/otheruser
Content-Type: application/json

{

}
